from src.db.connection import DatabaseConnection


class QueryExecutor:

    def __init__(self):
        self.db = DatabaseConnection()
        self.connection = self.db.connect()

    def execute(self, query, params=None):
        """
        Executes SQL query and returns results.

        query:
            SQL query generated by the agent

        params:
            Optional parameters for parameterized queries
        """

        with self.connection.cursor() as cursor:

            cursor.execute(query, params)

            # Check if query returns data
            if cursor.description:

                rows = cursor.fetchall()

                return rows

            else:
                # For INSERT, UPDATE, DELETE
                self.connection.commit()

                return {
                    "status": "success",
                    "rows_affected": cursor.rowcount
                }


    def close(self):
        self.db.close()